config/routes.rb
Rails.application.routes.draw do

  resources :accounts
  resources :rentals
  devise_for :users, controllers: { sessions: 'users/sessions' }

  # Ensure you have defined root_url to *something* in your config/routes.rb.
  resources :films
  get 'films/show'
  get 'films/title'
  get 'films/synopsis'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'films#index'
  match '/users',   to: 'users#index',   via: 'get'
  get 'users/:id', to: 'users#show', as: 'user'
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :film
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: [:show, :edit, :update, :destroy]

  # GET /rentals
  # GET /rentals.json
  def index
    @rentals = Rental.all
  end

  # GET /rentals/1
  # GET /rentals/1.json
  def show
    @film_title = Film.find(@rental.film_id).title
    @rentee_email = User.find(@rental.user_id).email
  end

  # GET /rentals/new
  def new
    @film_id = params[:film_id]
    @filmTitle = Film.find(@film_id).title
    @rental = Rental.new
  end

  # GET /rentals/1/edit
  def edit
  end

  # POST /rentals
  # POST /rentals.json
  def create
    @rental = Rental.new(rental_params)

    respond_to do |format|
      if @rental.save
        f = Film.find(@rental.film_id)
        f.rentable = false
        f.save!
        format.html { redirect_to @rental, notice: 'Rental was successfully created.' }
        format.json { render :show, status: :created, location: @rental }
      else
        format.html { render :new }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rentals/1
  # PATCH/PUT /rentals/1.json
  def update
    respond_to do |format|
      if @rental.update(rental_params)
        format.html { redirect_to @rental, notice: 'Rental was successfully updated.' }
        format.json { render :show, status: :ok, location: @rental }
      else
        format.html { render :edit }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rentals/1
  # DELETE /rentals/1.json
  def destroy
    @rental.destroy
    respond_to do |format|
      format.html { redirect_to rentals_url, notice: 'Rental was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental
      @rental = Rental.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rental_params
      params.require(:rental).permit(:film_id, :user_id, :due_date)
    end
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/rentals/_form.html.erb
<%= form_with(model: rental, local: true) do |form| %>
  <% if rental.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rental.errors.count, "error") %> prohibited this rental from being saved:</h2>

      <ul>
        <% rental.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Filmid %>
    <%= form.number_field :film_id, value: @film_id %>
    <%= @filmTitle %>
  </div>

  <div class="field">
    <%= form.label :Userid %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :Duedate %>
    <%= form.date_field :due_date %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rentals/edit.html.erb
<h1>Editing Rental</h1>

<%= render 'form', rental: @rental %>

<%= link_to 'Show', @rental %> |
<%= link_to 'Back', rentals_path %>

app/views/rentals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rentals</h1>

<table>
  <thead>
    <tr>
      <th>Film</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rentals.each do |rental| %>
      <tr>
        <td><%= link_to Film.find_by(id: rental.film_id).title, film_path(rental.film_id) %></td>
        <td><%= link_to User.find_by(id: rental.user_id).email, user_path(rental.user_id) %></td>
        <td><%= link_to 'Show', rental %></td>
        <td><%= link_to 'Edit', edit_rental_path(rental) %></td>
        <td><%= link_to 'Destroy', rental, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rental', new_rental_path %>

app/views/rentals/new.html.erb
<h1>New Rental</h1>

<%= render 'form', rental: @rental %>

<%= link_to 'Back', rentals_path %>

app/views/rentals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Film:</strong>
  <%= @film_title %>
</p>

<p>
  <strong>User:</strong>
  <%= @rentee_email %>
</p>

<%= link_to 'Edit', edit_rental_path(@rental) %> |
<%= link_to 'Back', rentals_path %>